main: net.notfab.hubbasics.HubBasics
version: 6.0-DEVELOPMENT
name: HubBasics
authors: [Fabricio20, Mister_2]
description: >
             HubBasics is a plugin containing settings, options and features you as a server owner might desire
commands: